### ISSUE TITLE
udp test command fails

### ISSUE THREAD

**Issue by ethaeris** [aeristhings/aeris-modsdk-py#9]
On a Raspberry Pi with Python 3.7.3 and commit 2e4b647b560fcbc651ff9fd6bd4d3528bc440ba3 of the aeris-modsdk-py, run:
`poetry run aeriscli --verbose udp test`

You will get a stacktrace like:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/.cache/pypoetry/virtualenvs/aerismodsdk-CICK1QfL-py3.7/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.cache/pypoetry/virtualenvs/aerismodsdk-CICK1QfL-py3.7/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/.cache/pypoetry/virtualenvs/aerismodsdk-CICK1QfL-py3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/.cache/pypoetry/virtualenvs/aerismodsdk-CICK1QfL-py3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/.cache/pypoetry/virtualenvs/aerismodsdk-CICK1QfL-py3.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.cache/pypoetry/virtualenvs/aerismodsdk-CICK1QfL-py3.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/.cache/pypoetry/virtualenvs/aerismodsdk-CICK1QfL-py3.7/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pi/git/aeris-modsdk-py/aerismodsdk/cli.py", line 382, in test
    start_time = time.time()
AttributeError: 'Command' object has no attribute 'time'
```

I have not verified whether or not other commands that use functions from the `time` import work.

It is suspected that this regression was introduced by d4b0d6e6b21f42984f274258866827e5481cfb4e: specifically, that the `time` command collides with the `time` import.

**Comment by drewjohnsonataeris** [comment]
I had ended up adding a command named as 'time' which caused a conflict with python time module. After, renaming, this problem goes away (at least in my testing).
